/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSchoolManagementRouteImport } from './routes/solutions.school-management'
import { Route as SolutionsEnterpriseErpRouteImport } from './routes/solutions.enterprise-erp'
import { Route as SolutionsAutomationDashboardsRouteImport } from './routes/solutions.automation-dashboards'
import { Route as IndustriesManufacturingRouteImport } from './routes/industries.manufacturing'
import { Route as IndustriesLogisticsRouteImport } from './routes/industries.logistics'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries.healthcare'
import { Route as IndustriesEducationRouteImport } from './routes/industries.education'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuditLeadRouteImport } from './routes/api/audit-lead'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSchoolManagementRoute =
  SolutionsSchoolManagementRouteImport.update({
    id: '/school-management',
    path: '/school-management',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsEnterpriseErpRoute = SolutionsEnterpriseErpRouteImport.update({
  id: '/enterprise-erp',
  path: '/enterprise-erp',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAutomationDashboardsRoute =
  SolutionsAutomationDashboardsRouteImport.update({
    id: '/automation-dashboards',
    path: '/automation-dashboards',
    getParentRoute: () => SolutionsRoute,
  } as any)
const IndustriesManufacturingRoute = IndustriesManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesLogisticsRoute = IndustriesLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesEducationRoute = IndustriesEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => IndustriesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLeadRoute = ApiAuditLeadRouteImport.update({
  id: '/api/audit-lead',
  path: '/api/audit-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/api/audit-lead': typeof ApiAuditLeadRoute
  '/api/chat': typeof ApiChatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/logistics': typeof IndustriesLogisticsRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/solutions/automation-dashboards': typeof SolutionsAutomationDashboardsRoute
  '/solutions/enterprise-erp': typeof SolutionsEnterpriseErpRoute
  '/solutions/school-management': typeof SolutionsSchoolManagementRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/api/audit-lead': typeof ApiAuditLeadRoute
  '/api/chat': typeof ApiChatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/logistics': typeof IndustriesLogisticsRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/solutions/automation-dashboards': typeof SolutionsAutomationDashboardsRoute
  '/solutions/enterprise-erp': typeof SolutionsEnterpriseErpRoute
  '/solutions/school-management': typeof SolutionsSchoolManagementRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/api/audit-lead': typeof ApiAuditLeadRoute
  '/api/chat': typeof ApiChatRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/logistics': typeof IndustriesLogisticsRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/solutions/automation-dashboards': typeof SolutionsAutomationDashboardsRoute
  '/solutions/enterprise-erp': typeof SolutionsEnterpriseErpRoute
  '/solutions/school-management': typeof SolutionsSchoolManagementRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/login'
    | '/sitemap.xml'
    | '/solutions'
    | '/api/audit-lead'
    | '/api/chat'
    | '/articles/$slug'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/logistics'
    | '/industries/manufacturing'
    | '/solutions/automation-dashboards'
    | '/solutions/enterprise-erp'
    | '/solutions/school-management'
    | '/admin/articles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/login'
    | '/sitemap.xml'
    | '/solutions'
    | '/api/audit-lead'
    | '/api/chat'
    | '/articles/$slug'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/logistics'
    | '/industries/manufacturing'
    | '/solutions/automation-dashboards'
    | '/solutions/enterprise-erp'
    | '/solutions/school-management'
    | '/admin/articles/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/login'
    | '/sitemap.xml'
    | '/solutions'
    | '/api/audit-lead'
    | '/api/chat'
    | '/articles/$slug'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/logistics'
    | '/industries/manufacturing'
    | '/solutions/automation-dashboards'
    | '/solutions/enterprise-erp'
    | '/solutions/school-management'
    | '/admin/articles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  ApiAuditLeadRoute: typeof ApiAuditLeadRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/school-management': {
      id: '/solutions/school-management'
      path: '/school-management'
      fullPath: '/solutions/school-management'
      preLoaderRoute: typeof SolutionsSchoolManagementRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/enterprise-erp': {
      id: '/solutions/enterprise-erp'
      path: '/enterprise-erp'
      fullPath: '/solutions/enterprise-erp'
      preLoaderRoute: typeof SolutionsEnterpriseErpRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/automation-dashboards': {
      id: '/solutions/automation-dashboards'
      path: '/automation-dashboards'
      fullPath: '/solutions/automation-dashboards'
      preLoaderRoute: typeof SolutionsAutomationDashboardsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/industries/manufacturing': {
      id: '/industries/manufacturing'
      path: '/manufacturing'
      fullPath: '/industries/manufacturing'
      preLoaderRoute: typeof IndustriesManufacturingRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/logistics': {
      id: '/industries/logistics'
      path: '/logistics'
      fullPath: '/industries/logistics'
      preLoaderRoute: typeof IndustriesLogisticsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/education': {
      id: '/industries/education'
      path: '/education'
      fullPath: '/industries/education'
      preLoaderRoute: typeof IndustriesEducationRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-lead': {
      id: '/api/audit-lead'
      path: '/api/audit-lead'
      fullPath: '/api/audit-lead'
      preLoaderRoute: typeof ApiAuditLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesIdRoute: AdminArticlesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesEducationRoute: typeof IndustriesEducationRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesLogisticsRoute: typeof IndustriesLogisticsRoute
  IndustriesManufacturingRoute: typeof IndustriesManufacturingRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesEducationRoute: IndustriesEducationRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesLogisticsRoute: IndustriesLogisticsRoute,
  IndustriesManufacturingRoute: IndustriesManufacturingRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsAutomationDashboardsRoute: typeof SolutionsAutomationDashboardsRoute
  SolutionsEnterpriseErpRoute: typeof SolutionsEnterpriseErpRoute
  SolutionsSchoolManagementRoute: typeof SolutionsSchoolManagementRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAutomationDashboardsRoute: SolutionsAutomationDashboardsRoute,
  SolutionsEnterpriseErpRoute: SolutionsEnterpriseErpRoute,
  SolutionsSchoolManagementRoute: SolutionsSchoolManagementRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  ApiAuditLeadRoute: ApiAuditLeadRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
